/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 系统部门信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISysDept extends Serializable {

    /**
     * Setter for <code>learn_jooq.sys_dept.id</code>. ID，自增主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>learn_jooq.sys_dept.id</code>. ID，自增主键
     */
    public Long getId();

    /**
     * Setter for <code>learn_jooq.sys_dept.name</code>. 部门名称
     */
    public void setName(String value);

    /**
     * Getter for <code>learn_jooq.sys_dept.name</code>. 部门名称
     */
    public String getName();

    /**
     * Setter for <code>learn_jooq.sys_dept.tel</code>. 电话号码
     */
    public void setTel(String value);

    /**
     * Getter for <code>learn_jooq.sys_dept.tel</code>. 电话号码
     */
    public String getTel();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISysDept
     */
    public void from(org.shiloh.jooq.codegen.tables.interfaces.ISysDept from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISysDept
     */
    public <E extends org.shiloh.jooq.codegen.tables.interfaces.ISysDept> E into(E into);
}
