/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 系统用户信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISysUser extends Serializable {

    /**
     * Setter for <code>learn_jooq.sys_user.id</code>. ID，自增主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>learn_jooq.sys_user.id</code>. ID，自增主键
     */
    public Long getId();

    /**
     * Setter for <code>learn_jooq.sys_user.username</code>. 用户名
     */
    public void setUsername(String value);

    /**
     * Getter for <code>learn_jooq.sys_user.username</code>. 用户名
     */
    public String getUsername();

    /**
     * Setter for <code>learn_jooq.sys_user.password</code>. 密码
     */
    public void setPassword(String value);

    /**
     * Getter for <code>learn_jooq.sys_user.password</code>. 密码
     */
    public String getPassword();

    /**
     * Setter for <code>learn_jooq.sys_user.age</code>. 年龄
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>learn_jooq.sys_user.age</code>. 年龄
     */
    public Integer getAge();

    /**
     * Setter for <code>learn_jooq.sys_user.sex</code>. 性别
     */
    public void setSex(String value);

    /**
     * Getter for <code>learn_jooq.sys_user.sex</code>. 性别
     */
    public String getSex();

    /**
     * Setter for <code>learn_jooq.sys_user.email</code>. 电子邮箱
     */
    public void setEmail(String value);

    /**
     * Getter for <code>learn_jooq.sys_user.email</code>. 电子邮箱
     */
    public String getEmail();

    /**
     * Setter for <code>learn_jooq.sys_user.dept_id</code>. 所在部门 ID
     */
    public void setDeptId(Long value);

    /**
     * Getter for <code>learn_jooq.sys_user.dept_id</code>. 所在部门 ID
     */
    public Long getDeptId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISysUser
     */
    public void from(org.shiloh.jooq.codegen.tables.interfaces.ISysUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISysUser
     */
    public <E extends org.shiloh.jooq.codegen.tables.interfaces.ISysUser> E into(E into);
}
