/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen.tables.pojos;


import javax.annotation.Generated;

import org.shiloh.jooq.codegen.tables.interfaces.ISysDept;


/**
 * 系统部门信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDeptPojo implements ISysDept {

    private static final long serialVersionUID = -975553992;

    private Long   id;
    private String name;
    private String tel;

    public SysDeptPojo() {}

    public SysDeptPojo(ISysDept value) {
        this.id = value.getId();
        this.name = value.getName();
        this.tel = value.getTel();
    }

    public SysDeptPojo(
        Long   id,
        String name,
        String tel
    ) {
        this.id = id;
        this.name = name;
        this.tel = tel;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getTel() {
        return this.tel;
    }

    @Override
    public void setTel(String tel) {
        this.tel = tel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDeptPojo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(tel);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISysDept from) {
        setId(from.getId());
        setName(from.getName());
        setTel(from.getTel());
    }

    @Override
    public <E extends ISysDept> E into(E into) {
        into.from(this);
        return into;
    }
}
