/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.shiloh.jooq.codegen.tables.TSysDept;
import org.shiloh.jooq.codegen.tables.TSysUser;
import org.shiloh.jooq.codegen.tables.records.SysDeptRecord;
import org.shiloh.jooq.codegen.tables.records.SysUserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>learn_jooq</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SysDeptRecord, Long> IDENTITY_SYS_DEPT = Identities0.IDENTITY_SYS_DEPT;
    public static final Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Identities0.IDENTITY_SYS_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysDeptRecord> KEY_SYS_DEPT_PRIMARY = UniqueKeys0.KEY_SYS_DEPT_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SysDeptRecord, Long> IDENTITY_SYS_DEPT = Internal.createIdentity(TSysDept.SYS_DEPT, TSysDept.SYS_DEPT.ID);
        public static Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Internal.createIdentity(TSysUser.SYS_USER, TSysUser.SYS_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<SysDeptRecord> KEY_SYS_DEPT_PRIMARY = Internal.createUniqueKey(TSysDept.SYS_DEPT, "KEY_sys_dept_PRIMARY", TSysDept.SYS_DEPT.ID);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(TSysUser.SYS_USER, "KEY_sys_user_PRIMARY", TSysUser.SYS_USER.ID);
    }
}
