/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.shiloh.jooq.codegen.tables.TSysDept;
import org.shiloh.jooq.codegen.tables.TSysUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LearnJooq extends SchemaImpl {

    private static final long serialVersionUID = 521908399;

    /**
     * The reference instance of <code>learn_jooq</code>
     */
    public static final LearnJooq LEARN_JOOQ = new LearnJooq();

    /**
     * 系统部门信息表
     */
    public final TSysDept SYS_DEPT = org.shiloh.jooq.codegen.tables.TSysDept.SYS_DEPT;

    /**
     * 系统用户信息表
     */
    public final TSysUser SYS_USER = org.shiloh.jooq.codegen.tables.TSysUser.SYS_USER;

    /**
     * No further instances allowed
     */
    private LearnJooq() {
        super("learn_jooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TSysDept.SYS_DEPT,
            TSysUser.SYS_USER);
    }
}
