/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen;


import javax.annotation.Generated;

import org.shiloh.jooq.codegen.tables.TSysDept;
import org.shiloh.jooq.codegen.tables.TSysUser;


/**
 * Convenience access to all tables in learn_jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 系统部门信息表
     */
    public static final TSysDept SYS_DEPT = TSysDept.SYS_DEPT;

    /**
     * 系统用户信息表
     */
    public static final TSysUser SYS_USER = TSysUser.SYS_USER;
}
